config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [path("admin/", admin.site.urls), path("", include("todo.urls"))]

todo/api/urls.py
from django.urls import include, path

urlpatterns = [
    path("v1/", include("todo.api.v1.urls")),
]

todo/api/v1/urls.py
from django.urls import include, path

from .router import router

urlpatterns = [path("", include(router.urls))]

todo/urls.py
from django.urls import include, path

from todo.views import (
    TasksCreateView,
    TasksDeleteView,
    TasksListView,
    TasksUpdateIsDoneView,
    TasksActiveListView
)

app_name = "todo"

urlpatterns = [
    path("", TasksListView.as_view(), name="index"),
    path("active", TasksActiveListView.as_view(), name="active"),
    path("create", TasksCreateView.as_view(), name="create"),
    path("update/<int:pk>", TasksUpdateIsDoneView.as_view(), name="update"),
    path("delete/<int:pk>", TasksDeleteView.as_view(), name="delete"),
    path("api/", include("todo.api.urls")),
]

todo/models.py
from django.db import models


class Tasks(models.Model):
    """Задача"""

    title = models.CharField(max_length=255, verbose_name="Наименование")
    is_active = models.BooleanField(verbose_name="Выполнена", default=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    completed_at = models.DateTimeField(
        verbose_name="Время завершения", blank=True, null=True
    )

    class Meta:
        verbose_name = "Задача"
        verbose_name_plural = "Задачи"

todo/forms.py
from django import forms

from .models import Tasks


class TasksModelForm(forms.ModelForm):
    """Задача"""

    class Meta:
        model = Tasks
        fields = ["title"]

todo/api/v1/views.py
from django_filters import rest_framework as filters
from rest_framework import viewsets
from rest_framework.filters import OrderingFilter, SearchFilter

from todo.models import Tasks

from .serializer import TasksSerializer


class TasksFilter(filters.FilterSet):
    class Meta:
        model = Tasks
        fields = ("title", "is_active")


class TasksViewSet(viewsets.ModelViewSet):
    serializer_class = TasksSerializer
    queryset = Tasks.objects.all()
    filter_backends = (OrderingFilter, filters.DjangoFilterBackend, SearchFilter)
    filterset_class = TasksFilter
    ordering_fields = ["title", "is_active", "completed_at"]
    search_fields = ["$title"]

todo/views.py
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, DeleteView, ListView, View

from .forms import TasksModelForm
from .models import Tasks


class TasksListView(ListView):
    """Список задач"""

    model = Tasks
    template_name = "todo/list.html"


class TasksActiveListView(View):
    """Список задач"""

    @staticmethod
    def get(request):
        return render(request, "todo/list.html", {
            "tasks_list": Tasks.objects.filter(is_active=True).all()
        })


class TasksCreateView(CreateView):
    """Создание задачи"""

    template_name = "todo/create.html"
    form_class = TasksModelForm
    success_url = reverse_lazy("todo:index")


class TasksUpdateIsDoneView(View):
    """Редактирование статуса задачи"""

    @staticmethod
    def post(request, pk):
        item = Tasks.objects.filter(id=pk).first()
        if item.is_active:
            Tasks.objects.filter(id=pk).update(is_active=False, completed_at=timezone.now())
        else:
            Tasks.objects.filter(id=pk).update(is_active=True, completed_at=None)
        return redirect("todo:index")


class TasksDeleteView(DeleteView):
    """Удаление задачи"""

    model = Tasks
    template_name = "todo/delete.html"
    success_url = reverse_lazy("todo:index")

todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">

    {% block title %}
    {% endblock %}

    {% load static %}
    <link href="{% static 'todo/css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'todo/css/sticky-footer-navbar.css'%}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>

     <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>


</head>
<body class="d-flex flex-column h-100">

<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'todo:index' %}" class="nav-link px-2 link-secondary">Главная</a></li>
    </header>
</div>

<main class="flex-shrink-0">
    <div class="container">

        {% block content %}
        {% endblock %}


    </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="{% url 'todo:index' %}" class="nav-link px-2 text-muted">Главная</a></li>
        </ul>
        <p class="text-center text-muted">Список дел</p>
    </div>
</footer>

 <script>
        $(function () {
            $("#datetimepicker1").datetimepicker({
                format: 'DD/MM/YYYY HH:mm',
            });
        });
    </script>

</body>
</html>

todo/templates/todo/create.html
{% extends "todo/base.html" %}

{% block title %}
<title>Создать задачу</title>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
            {{ field|as_crispy_field }}
            {% endfor %}
            <button class="w-100 btn btn-lg btn-primary mt-5" type="submit">Сохранить</button>
        </form>
    </div>
    <div class="col-4"></div>
</div>
{% endblock %}

todo/templates/todo/delete.html
{% extends "todo/base.html" %}

{% block title %}
    <title>Удаление задачи</title>
{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        <p>Вы уверены, что хотите удалить задача: <b>"{{ item.title }}"</b> ?</p>
        <input type="submit" class="btn btn-sm btn-outline-danger rounded-pill" value="Удалить" />
    </form>

{% endblock %}

todo/templates/todo/list.html
{% extends "todo/base.html" %}

{% block title %}
<title>Список дел</title>
{% endblock %}

{% block content %}
{% load tz %}
<div>
    <a href="{% url 'todo:create' %}" class="btn btn-primary">Добавить</a>
</div>

{% if tasks_list %}
<table class="table table-striped">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Выполено</th>
        <th scope="col">Название</th>
        <th scope="col">Дата выполнения</th>
        <th scope="col">Управление</th>
    </tr>
    </thead>
    <tbody>

    {% for model in tasks_list %}
    <tr>
        <th scope="row">{{forloop.counter}}</th>
        <td>

            <form method="post" action="{% url 'todo:update' model.id %}">
                {% csrf_token %}
                <div class="form-check form-switch">
                    {% if not model.is_active %}
                    <input class="form-check-input" type="checkbox" onclick="javascript:submit()" role="switch" checked >
                    {% else %}
                    <input class="form-check-input" type="checkbox" onclick="javascript:submit()" role="switch">
                    {% endif %}
                </div>
            </form>

        </td>
        <td>{{ model.title }}</td>

        <td>
            {% if model.completed_at %}
            {{ model.completed_at|localtime }}
            {% else %}
            -
            {% endif %}
        </td>
        <td>
            <a href="{% url 'todo:delete' model.id %}" class="btn btn-danger">
                Удалить
            </a>
        </td>

    </tr>
    {% endfor %}

    {% else %}
    <p>Список дел еще нет</p>
    {% endif %}

    </tbody>
</table>
{% endblock %}